---
# Global variables for Kubernetes cluster setup

# System configuration
timezone: "Asia/Ho_Chi_Minh"
ntp_servers:
  - "pool.ntp.org"
  - "time.google.com"

# Container runtime configuration
containerd_version: "latest"
containerd_config_dir: "/etc/containerd"
containerd_socket: "/run/containerd/containerd.sock"

# Kubernetes configuration
kubernetes_version: "1.33.2"
kubelet_version: "1.33.2"
kubectl_version: "1.33.2"
kubeadm_version: "1.33.2"

# Cluster networking (Calico default CIDR)
pod_network_cidr: "192.168.0.0/16"
service_cidr: "10.96.0.0/12"
cluster_dns: "10.96.0.10"

# CNI plugin (Calico)
calico_version: "3.27.0"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"

# System requirements
min_memory_gb: 2
min_cpu_cores: 2
min_disk_gb: 20

# Firewall rules
firewall_rules:
  - port: 6443
    protocol: tcp
    description: "Kubernetes API server"
  - port: 2379-2380
    protocol: tcp
    description: "etcd server client API"
  - port: 10250
    protocol: tcp
    description: "Kubelet API"
  - port: 10251
    protocol: tcp
    description: "kube-scheduler"
  - port: 10252
    protocol: tcp
    description: "kube-controller-manager"
  - port: 10255
    protocol: tcp
    description: "Read-only Kubelet API"
  - port: 30000-32767
    protocol: tcp
    description: "NodePort Services"

# Package repositories
docker_repo_url: "https://download.docker.com/linux/ubuntu"
kubernetes_repo_url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version | regex_replace('^([0-9]+\\.[0-9]+).*', '\\1') }}/deb"
