---
# Variables specific to Kubernetes master nodes

# Master node configuration
master_node_type: "master"
kubelet_extra_args: "--node-labels=node-role.kubernetes.io/master= --register-with-taints=node-role.kubernetes.io/master=:NoSchedule"

# Control plane configuration
control_plane_endpoint: "{{ load_balancer_ip | default(groups['k8s_masters'][0]) }}:6443"
api_server_cert_extra_sans:
  - "{{ load_balancer_ip | default('') }}"
  - "{{ ansible_default_ipv4.address }}"
  - "localhost"
  - "127.0.0.1"

# etcd configuration
etcd_data_dir: "/var/lib/etcd"
etcd_backup_dir: "/opt/etcd-backup"

# High availability configuration
ha_enabled: true
ha_vip: "{{ load_balancer_ip | default('') }}"
ha_vip_interface: "{{ ansible_default_ipv4.interface }}"

# Master specific firewall rules
master_firewall_rules:
  - port: 6443
    protocol: tcp
    description: "Kubernetes API server"
  - port: 2379-2380
    protocol: tcp
    description: "etcd server client API"
  - port: 10250
    protocol: tcp
    description: "Kubelet API"
  - port: 10251
    protocol: tcp
    description: "kube-scheduler"
  - port: 10252
    protocol: tcp
    description: "kube-controller-manager"
  - port: 10255
    protocol: tcp
    description: "Read-only Kubelet API"
