---
- name: Install and configure containerd
  hosts: k8s_cluster
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd
        state: present

    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate containerd default configuration
      shell: |
        containerd config default \
        | sed 's/SystemdCgroup = false/SystemdCgroup = true/' \
        | sed 's|sandbox_image = ".*"|sandbox_image = "registry.k8s.io/pause:3.10"|' \
        > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Start and enable containerd service
      systemd:
        name: containerd
        state: started
        enabled: yes

    - name: Disable swap
      shell: |
        swapoff -a
      args:
        warn: false

    - name: Install CNI plugins
      unarchive:
        src: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
        dest: /opt/cni/bin
        remote_src: yes
        mode: '0755'

    - name: Create CNI configuration directory
      file:
        path: /etc/cni/net.d
        state: directory
        mode: '0755'

  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
