---
- name: Install Kubernetes components
  hosts: k8s_cluster
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages for Kubernetes repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Create Kubernetes keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version | regex_replace('^([0-9]+\\.[0-9]+).*', '\\1') }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{ kubernetes_repo_url }} /' | tee /etc/apt/sources.list.d/kubernetes.list
      args:
        creates: /etc/apt/sources.list.d/kubernetes.list

    - name: Update package cache after adding Kubernetes repository
      apt:
        update_cache: yes


    - name: Install Kubernetes components
      apt:
        name:
          - kubelet={{ kubelet_version }}-1.1
          - kubeadm={{ kubeadm_version }}-1.1
          - kubectl={{ kubectl_version }}-1.1
        state: present

    - name: Hold Kubernetes packages to prevent automatic updates
      shell: |
        apt-mark hold kubelet kubeadm kubectl

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Enable IP forwarding permanently
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#net\.ipv4\.ip_forward=1'
        line: 'net.ipv4.ip_forward=1'
        state: present

    - name: Apply sysctl configuration
      shell: sysctl -p

    - name: Start and enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

  handlers:
    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted
