---
- name: Join worker nodes to Kubernetes cluster
  hosts: k8s_workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Get join command from master
      slurp:
        src: /tmp/join-command.sh
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: join_command_file

    - name: Decode join command
      set_fact:
        join_command: "{{ join_command_file.content | b64decode | trim }}"

    - name: Join worker node to cluster
      command: "{{ join_command }}"
      register: join_result
      args:
        creates: /etc/kubernetes/kubelet.conf
      retries: 3
      delay: 10

    - name: Wait for node to be ready
      wait_for:
        host: "{{ groups['k8s_masters'][0] }}"
        port: 6443
        delay: 10
        timeout: 300
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Verify node joined successfully
      shell: kubectl get nodes
      register: nodes_status
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      when: join_result is succeeded

    - name: Display nodes status
      debug:
        msg: "{{ nodes_status.stdout_lines }}"
      when: nodes_status is succeeded
